version: '3.8'
services:
  app:
    build: .
    links:
      - db
    ports:
      - "5000:5000"
    depends_on:
      - db
    networks:
      - backend


  db:
    image: mysql:latest
    ports:
      - "3306:3306"
    environment:
       - MYSQL_ROOT_PASSWORD=""
       - MYSQL_DATABASE=genai_flask_db
       - MYSQL_USER=root
       - MYSQL_PASSWORD=""
    volumes:
      - ./data:/var/lib/mysql
    restart: always
    networks:
      - backend

networks:
  backend: